# Generated by Django 3.0.3 on 2020-11-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipamentos',
            new_name='Equipamento',
        ),
    ]
